@Backend_HostAddress = https://localhost:7189


### CREATE License
POST {{Backend_HostAddress}}/api/licenses/
Content-Type: application/json

{
  "number": "LN-12-3456",
  "typeId": 1,
  "statusId": 1,
  "issuanceDate": "2025-10-05",
  "validity": 5,
  "firstName": "Juan",
  "middleName": "Garcia",
  "lastName": "Dela Cruz",
  "birthDate": "2005-06-07",
  "sex": "M",
  "address": "Sta. Ana, Manila City",
  "nationality": "Filipino",
  "eyeColor": "Brown",
  "height": 170,
  "weight": 60,
  "bloodType": "AB+"
}

### GET License
@licenseNumber = LN-12-3456
GET {{Backend_HostAddress}}/api/licenses/{{licenseNumber}}

### DELETE License
@licenseId = 2
DELETE {{Backend_HostAddress}}/api/licenses/{{licenseId}}


### CREATE Vehicle
POST {{Backend_HostAddress}}/api/vehicles/
Content-Type: application/json

{
  "plateNumber": "ABC 1234",
  "mvFileNumber": "XYZ6767",
  "vin": "987654321",
  "registerIssuanceDate": "2026-02-01",
  "validity": 3,
  "make": "Toyota",
  "model": "Innova",
  "year": "2026",
  "color": "Silver",
  "licenseNumber": "LN-12-3456"
}

### GET Vehicle
@plateOrMvFileNum = ABC 1234
GET {{Backend_HostAddress}}/api/vehicles/{{plateOrMvFileNum}}

### DELETE Vehicle
@vehicleId = 99
DELETE {{Backend_HostAddress}}/api/vehicles/{{vehicleId}}


### CREATE Account
POST {{Backend_HostAddress}}/api/accounts/
Content-Type: application/json

{
  "email": "sample@gmail.com",
  "password": "passwordpassword",
  "roleId": 1,
  "licenseNumber": "LN-12-3456"
}

### GET Account
@accountId = 5
GET {{Backend_HostAddress}}/api/accounts/{{accountId}}

### DELETE Account
DELETE {{Backend_HostAddress}}/api/accounts/{{accountId}}