// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileDataTerminal.Api.Data;

#nullable disable

namespace MobileDataTerminal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718175841_InitialTicketing")]
    partial class InitialTicketing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_blood_types_name");

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A+"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A-"
                        },
                        new
                        {
                            Id = 3,
                            Name = "B+"
                        },
                        new
                        {
                            Id = 4,
                            Name = "B-"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AB+"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AB-"
                        },
                        new
                        {
                            Id = 7,
                            Name = "O+"
                        },
                        new
                        {
                            Id = 8,
                            Name = "O-"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.EyeColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_eye_colors_name");

                    b.ToTable("EyeColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hazel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Amber"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("EyeColorId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<DateOnly>("IssuanceDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("EyeColorId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("uq_licenses_number");

                    b.HasIndex("SexId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.LicenseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_license_statuses_name");

                    b.ToTable("LicenseStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Revoked"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Expired"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.LicenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_license_types_name");

                    b.ToTable("LicenseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Professional"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NonProfessional"
                        },
                        new
                        {
                            Id = 3,
                            Name = "StudentPermit"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_nationalities_name");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Filipino"
                        },
                        new
                        {
                            Id = 2,
                            Name = "American"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SouthKorean"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Taiwanese"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Singaporean"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Malaysian"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Indonesian"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Thai"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cambodian"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = 13,
                            Name = "British"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Australian"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Canadian"
                        },
                        new
                        {
                            Id = 16,
                            Name = "NewZealander"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Mexican"
                        },
                        new
                        {
                            Id = 20,
                            Name = "German"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = 22,
                            Name = "French"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Swiss"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Swedish"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Norwegian"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 29,
                            Name = "SouthAfrican"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Indian"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.Sex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_sexes_name");

                    b.ToTable("Sexes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Ticketing.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentPlace")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("LicenseId")
                        .HasColumnType("int");

                    b.Property<string>("OfficerNotes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SettledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_tickets_reference_number");

                    b.HasIndex("StatusId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Ticketing.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_ticket_statuses_name");

                    b.ToTable("TicketStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Unsettled"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Settled"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Ticketing.TicketViolation", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("ViolationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fine")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("TicketId", "ViolationId");

                    b.HasIndex("ViolationId");

                    b.ToTable("TicketViolations");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Ticketing.Violation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("InitialFine")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsTiered")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SecondFine")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ThirdFine")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_violations_name");

                    b.ToTable("Violations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InitialFine = 3000m,
                            IsTiered = false,
                            Name = "DRIVING WITHOUT VALID LICENSE"
                        },
                        new
                        {
                            Id = 2,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "FAILURE TO CARRY LICENSE"
                        },
                        new
                        {
                            Id = 3,
                            InitialFine = 3000m,
                            IsTiered = false,
                            Name = "FAKE DRIVER'S LICENSE"
                        },
                        new
                        {
                            Id = 4,
                            InitialFine = 10000m,
                            IsTiered = false,
                            Name = "DRIVING UNREGISTERED VEHICLE"
                        },
                        new
                        {
                            Id = 5,
                            InitialFine = 5000m,
                            IsTiered = false,
                            Name = "ILLEGAL MODIFICATIONS"
                        },
                        new
                        {
                            Id = 6,
                            InitialFine = 5000m,
                            IsTiered = false,
                            Name = "DEFECTIVE/IMPROPER EQUIPMENT"
                        },
                        new
                        {
                            Id = 7,
                            InitialFine = 2000m,
                            IsTiered = true,
                            Name = "RECKLESS DRIVING",
                            SecondFine = 3000m,
                            ThirdFine = 10000m
                        },
                        new
                        {
                            Id = 8,
                            InitialFine = 1000m,
                            IsTiered = true,
                            Name = "NO SEATBELT",
                            SecondFine = 3000m,
                            ThirdFine = 5000m
                        },
                        new
                        {
                            Id = 9,
                            InitialFine = 1500m,
                            IsTiered = true,
                            Name = "NO HELMET",
                            SecondFine = 3000m,
                            ThirdFine = 5000m
                        },
                        new
                        {
                            Id = 10,
                            InitialFine = 20000m,
                            IsTiered = true,
                            Name = "DRIVING UNDER INFLUENCE",
                            SecondFine = 50000m,
                            ThirdFine = 100000m
                        },
                        new
                        {
                            Id = 11,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "OBSTRUCTION"
                        },
                        new
                        {
                            Id = 12,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "NO OR/CR"
                        },
                        new
                        {
                            Id = 13,
                            InitialFine = 2000m,
                            IsTiered = false,
                            Name = "OVERLOADING PASSENGERS"
                        },
                        new
                        {
                            Id = 14,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "OVER-SPEEDING"
                        },
                        new
                        {
                            Id = 15,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "BEATING THE RED LIGHT"
                        },
                        new
                        {
                            Id = 16,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "ILLEGAL PARKING"
                        },
                        new
                        {
                            Id = 17,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "USING PHONE WHILE DRIVING"
                        },
                        new
                        {
                            Id = 18,
                            InitialFine = 2000m,
                            IsTiered = false,
                            Name = "COUNTERFLOWING"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.HasIndex("LicenseId")
                        .IsUnique()
                        .HasDatabaseName("uq_users_license_id")
                        .HasFilter("[LicenseId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_users_username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_user_roles_name");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Civilian"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Officer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Vehicles.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MvFileNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("RegisterExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RegisterIssuanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.HasIndex("MvFileNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_mv_file_number")
                        .HasFilter("[MvFileNumber] IS NOT NULL");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_plate_number");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_vin");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.License", b =>
                {
                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.BloodType", "BloodType")
                        .WithMany()
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_blood_types");

                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.EyeColor", "EyeColor")
                        .WithMany()
                        .HasForeignKey("EyeColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_eye_colors");

                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_nationalities");

                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_sexes");

                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.LicenseStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_statuses");

                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.LicenseType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_types");

                    b.Navigation("BloodType");

                    b.Navigation("EyeColor");

                    b.Navigation("Nationality");

                    b.Navigation("Sex");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Ticketing.Ticket", b =>
                {
                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_licenses");

                    b.HasOne("MobileDataTerminal.Api.Features.Ticketing.TicketStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Ticketing.TicketViolation", b =>
                {
                    b.HasOne("MobileDataTerminal.Api.Features.Ticketing.Ticket", "Ticket")
                        .WithMany("TicketViolations")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_violations_tickets");

                    b.HasOne("MobileDataTerminal.Api.Features.Ticketing.Violation", "Violation")
                        .WithMany()
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_violations_violations");

                    b.Navigation("Ticket");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Users.User", b =>
                {
                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.License", "License")
                        .WithOne()
                        .HasForeignKey("MobileDataTerminal.Api.Features.Users.User", "LicenseId")
                        .HasConstraintName("fk_users_licenses");

                    b.HasOne("MobileDataTerminal.Api.Features.Users.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_roles");

                    b.Navigation("License");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Vehicles.Vehicle", b =>
                {
                    b.HasOne("MobileDataTerminal.Api.Features.Licenses.License", "License")
                        .WithMany("Vehicles")
                        .HasForeignKey("LicenseId")
                        .HasConstraintName("fk_vehicles_licenses");

                    b.Navigation("License");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Licenses.License", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("MobileDataTerminal.Api.Features.Ticketing.Ticket", b =>
                {
                    b.Navigation("TicketViolations");
                });
#pragma warning restore 612, 618
        }
    }
}
