// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704135904_SeedViolations")]
    partial class SeedViolations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("integer")
                        .HasColumnName("license_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_email");

                    b.HasIndex("LicenseId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_license_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_accounts_role_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_username");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.AccountRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_account_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_account_roles_name");

                    b.ToTable("account_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Civilian"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Officer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Backend.Entities.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("blood_type");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("eye_color");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<DateOnly>("IssuanceDate")
                        .HasColumnType("date")
                        .HasColumnName("issuance_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nationality");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_licenses");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("uq_licenses_number");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_licenses_status_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_licenses_type_id");

                    b.ToTable("licenses", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.LicenseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_license_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_license_statuses_name");

                    b.ToTable("license_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Revoked"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Expired"
                        });
                });

            modelBuilder.Entity("Backend.Entities.LicenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_license_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_license_types_name");

                    b.ToTable("license_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Non-Professional"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Professional"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Student Permit"
                        });
                });

            modelBuilder.Entity("Backend.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("incident_place");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer")
                        .HasColumnName("license_id");

                    b.Property<string>("OfficerNotes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("officer_notes");

                    b.Property<decimal>("ReferenceNumber")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("reference_number");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ticket");

                    b.HasIndex("LicenseId")
                        .HasDatabaseName("ix_ticket_license_id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_tickets_reference_number");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.TicketViolation", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<int>("ViolationId")
                        .HasColumnType("integer")
                        .HasColumnName("violation_id");

                    b.Property<decimal>("FineCharged")
                        .HasColumnType("numeric")
                        .HasColumnName("fine_charged");

                    b.HasKey("TicketId", "ViolationId")
                        .HasName("pk_ticket_violation");

                    b.HasIndex("ViolationId")
                        .HasDatabaseName("ix_ticket_violation_violation_id");

                    b.ToTable("ticket_violation", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer")
                        .HasColumnName("license_id");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("model");

                    b.Property<string>("MvFileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mv_file_number");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("plate_number");

                    b.Property<DateOnly>("RegisterExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("register_expiry_date");

                    b.Property<DateOnly>("RegisterIssuanceDate")
                        .HasColumnType("date")
                        .HasColumnName("register_issuance_date");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("LicenseId")
                        .HasDatabaseName("ix_vehicles_license_id");

                    b.HasIndex("MvFileNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_mv_file_number");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_plate_number");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_vin");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Backend.Entities.Violation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("InitialFine")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_fine");

                    b.Property<bool>("IsTiered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tiered");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal?>("SecondFine")
                        .HasColumnType("numeric")
                        .HasColumnName("second_fine");

                    b.Property<decimal?>("ThirdFine")
                        .HasColumnType("numeric")
                        .HasColumnName("third_fine");

                    b.HasKey("Id")
                        .HasName("pk_violations");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_violations_name");

                    b.ToTable("violations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InitialFine = 3000m,
                            IsTiered = false,
                            Name = "DRIVING WITHOUT VALID LICENSE"
                        },
                        new
                        {
                            Id = 2,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "FAILURE TO CARRY LICENSE"
                        },
                        new
                        {
                            Id = 3,
                            InitialFine = 3000m,
                            IsTiered = false,
                            Name = "FAKE DRIVER'S LICENSE"
                        },
                        new
                        {
                            Id = 4,
                            InitialFine = 10000m,
                            IsTiered = false,
                            Name = "DRIVING UNREGISTERED VEHICLE"
                        },
                        new
                        {
                            Id = 5,
                            InitialFine = 5000m,
                            IsTiered = false,
                            Name = "ILLEGAL MODIFICATIONS"
                        },
                        new
                        {
                            Id = 6,
                            InitialFine = 5000m,
                            IsTiered = false,
                            Name = "DEFECTIVE/IMPROPER EQUIPMENT"
                        },
                        new
                        {
                            Id = 7,
                            InitialFine = 2000m,
                            IsTiered = true,
                            Name = "RECKLESS DRIVING",
                            SecondFine = 3000m,
                            ThirdFine = 10000m
                        },
                        new
                        {
                            Id = 8,
                            InitialFine = 1000m,
                            IsTiered = true,
                            Name = "NO SEATBELT",
                            SecondFine = 3000m,
                            ThirdFine = 5000m
                        },
                        new
                        {
                            Id = 9,
                            InitialFine = 1500m,
                            IsTiered = true,
                            Name = "NO HELMET",
                            SecondFine = 3000m,
                            ThirdFine = 5000m
                        },
                        new
                        {
                            Id = 10,
                            InitialFine = 20000m,
                            IsTiered = true,
                            Name = "DRIVING UNDER INFLUENCE",
                            SecondFine = 50000m,
                            ThirdFine = 100000m
                        },
                        new
                        {
                            Id = 11,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "OBSTRUCTION"
                        },
                        new
                        {
                            Id = 12,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "NO OR/CR"
                        },
                        new
                        {
                            Id = 13,
                            InitialFine = 2000m,
                            IsTiered = false,
                            Name = "OVERLOADING PASSENGERS"
                        },
                        new
                        {
                            Id = 14,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "OVER-SPEEDING"
                        },
                        new
                        {
                            Id = 15,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "BEATING THE RED LIGHT"
                        },
                        new
                        {
                            Id = 16,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "ILLEGAL PARKING"
                        },
                        new
                        {
                            Id = 17,
                            InitialFine = 1000m,
                            IsTiered = false,
                            Name = "USING PHONE WHILE DRIVING"
                        },
                        new
                        {
                            Id = 18,
                            InitialFine = 2000m,
                            IsTiered = false,
                            Name = "COUNTERFLOWING"
                        });
                });

            modelBuilder.Entity("Backend.Entities.Account", b =>
                {
                    b.HasOne("Backend.Entities.License", "License")
                        .WithOne()
                        .HasForeignKey("Backend.Entities.Account", "LicenseId")
                        .HasConstraintName("fk_accounts_licenses");

                    b.HasOne("Backend.Entities.AccountRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_account_roles");

                    b.Navigation("License");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Entities.License", b =>
                {
                    b.HasOne("Backend.Entities.LicenseStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_license_statuses");

                    b.HasOne("Backend.Entities.LicenseType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_license_types");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Backend.Entities.Ticket", b =>
                {
                    b.HasOne("Backend.Entities.License", "License")
                        .WithMany("Tickets")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_licenses");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Backend.Entities.TicketViolation", b =>
                {
                    b.HasOne("Backend.Entities.Ticket", "Ticket")
                        .WithMany("TicketViolations")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_violations_tickets");

                    b.HasOne("Backend.Entities.Violation", "Violation")
                        .WithMany()
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_violations_violations");

                    b.Navigation("Ticket");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("Backend.Entities.Vehicle", b =>
                {
                    b.HasOne("Backend.Entities.License", "License")
                        .WithMany("Vehicles")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_licenses");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Backend.Entities.License", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Backend.Entities.Ticket", b =>
                {
                    b.Navigation("TicketViolations");
                });
#pragma warning restore 612, 618
        }
    }
}
